# Generated by Django 3.2.18 on 2023-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_add_address_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(choices=[('cs', 'Czech'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('he', 'Hebrew'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('it', 'Italian'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('ky', 'Kyrgyz'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('uz', 'Uzbek')], default='en', max_length=35),
        ),
    ]
